CREATE TABLE IF NOT EXISTS `mod_hotspot` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `map_id` INT NOT NULL,
  `x` FLOAT NOT NULL,
  `y` FLOAT NOT NULL,
  `z` FLOAT NOT NULL,
  `radius` FLOAT NOT NULL DEFAULT 50.0,
  `xp_multiplier` FLOAT NOT NULL DEFAULT 3.0,
  `respawn_multiplier` FLOAT NOT NULL DEFAULT 0.05,
  `type` TINYINT NOT NULL DEFAULT 1,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `creature_entry` INT NOT NULL DEFAULT 0,
  `max_population` INT NOT NULL DEFAULT 10,
  `comment` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
